### PR TITLE
issue62 - Updated protocol doc

### PR DESCRIPTION
**Pull request by juliano60**
@artem-kim @michowski @claudist @ZacTredger 
Could you please review?

I am including you all so you are all aware of this document.

Kindest Regards,
Jules

### CODE REVIEW

**Review by michowski — COMMENTED** [review]
Hi Jules,

The disadvantage of the docx format is that it's no longer a text file. So diffs are harder to track, not visible on GitHub, no history in git, etc.

Could we consider a markdown file (`.md`) instead? I believe it was built specifically for such purposes.

Best,
Arek

**Comment by juliano60** [comment]
@michowski ,
Good suggestion. I shall convert!

Kindest Regards,
Jules

**Review by michowski — COMMENTED** [review]
Hi Jules,

HTML (which I believe is a subset of MD) would work too. Have you considered the pure markdown though? https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

I believe you could use a converter (or your editor) to now obtain MD from it. It is a lighter and more universal format than HTML, though tables aren't perfect there...

Best,
Arek

**Comment by juliano60** [comment]
Hi Arek,
Yes I tried Github's own markup, which works fine for a table with headers but has no way of drawing a table without headers! So  I fell back to HTML, which is what it gets converted into ultimately.

Kindest Regards,
Jules

**Comment by michowski** [comment]
I see. Shall we then rename the file to have an `.html` extension?

**Comment by juliano60** [comment]
Arek,

You can have both Github's markup and html in the file. If you rename to html you can only have html in the file.

Kindest Regards,
Jules

**Comment by michowski** [comment]
I see. Let's give it a try!

**Review by michowski — APPROVED** [review]

**Pull request merged**
