### PR TITLE
88 UI login instruction

### PR DESCRIPTION
**Pull request by claudist**
Added simple text below welcome banner, so clear for user on how to log in

I'm thinking to also add detail on how to register if new user. I know this detail is in protocol md.. so other suggestion would be to tell user to refer to protocol.md file?

### CODE REVIEW

**Review by michowski — DISMISSED** [review]
Awesome!

**Comment by claudist** [comment]
image

**Comment by claudist** [comment]
> Awesome!

I've added registration instruction ready for your approval :)

**Review by michowski — APPROVED** [review]
:rocket: :rocket: :rocket:

**Pull request merged**
